# Generated by Django 2.2.11 on 2020-03-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='_imported_date',
            new_name='imported_date',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='_step',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='_type',
            new_name='typee',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='_value',
            new_name='value',
        ),
    ]
